name: Yago Nobre Blog
description: Yet another linux operation blog.
meta_description: "Yet another linux operation blog."

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'https://yagonobre.com'
google_analytics: 'UA-86895467-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://yagonobre.com'
author:         'Yago Nobre'
authorTwitter:  'yagoyns'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
